### ISSUE TITLE
Learn more button does not read image properly (even for those community which has image uploaded)

### ISSUE THREAD

**Issue by ExtraShotLatte** [Jnjy/Orbital-2022#43]
![image](https://user-images.githubusercontent.com/58366602/175481750-45467d8b-26f5-4d78-beab-23993182a5f5.png)
![image](https://user-images.githubusercontent.com/58366602/175481775-8797e0b2-bf26-4a64-841b-e03541209afa.png)

**Comment by ExtraShotLatte** [comment]
Likely state updates / with the way we are passing info to the moreInfo element (since they are generated differently)

**Comment by Jnjy** [comment]
Fixed. Image source in img is not linked to the image in DB.
