### ISSUE TITLE
Cannot delete item

### ISSUE THREAD

**Issue by ExtraShotLatte** [Jnjy/Orbital-2022#52]
Unable to delete item (no button / code)

**Comment by Jnjy** [comment]
Current plan of attack is to create an item listing page. The item list will only include items posted by specific users, hence only allowing users to modify or delete their own items. Same will be done for item request page.

**Comment by Jnjy** [comment]
Item list page is roughly up, need to communicate with DB to print out all item posted by a specific user.

**Comment by ExtraShotLatte** [comment]
#60 will help in this

**Comment by Jnjy** [comment]
- need a new field to store community name in item doc.
- action button is up but currently thinking of plan of attack to delete item.

**Comment by ExtraShotLatte** [comment]
Fixed in #63, will proceed to close issue
